### PR TITLE
Fix package names, add a few more

### PR DESCRIPTION
**Pull request by antony**
I figured the first item should always be the npm package name including namespace - please correct if not?

### CODE REVIEW

**Comment by ryanatkn** [comment]
This is great, thank you!

A few notes:

- `@beyonk/svelte-mapbox` is already included under the heading _"integrations with other libraries"_, which itself is a subsection of _"misc libraries"_. I thought it made sense to separate out components that have significant 3rd party dependencies, but I'm open to suggestions to change things. The current distinction between components and libraries is messy and misleading, so maybe they should all be collapsed into one thing, with domain-specific headings. (e.g. _"map components"_ under a top-level _"components and other libraries"_ or something)
- `@beyonk/svelte-googlemaps` should go next to mapbox, wherever they end up.
- If no section changes are made, the following belong under the heading _"integrations with other libraries"_, but maybe it's time to reorganize - `@beyonk/svelte-facebook-pixel`, `@beyonk/svelte-facebook-customer-chat`, `@beyonk/svelte-google-analytics`
- The existing formatting has newlines after each `-` - looks like some of your additions don't have it.
- I have been considering Sapper resources like `@beyonk/sapper-httpclient` to be outside the scope of this list, but I'm open to including them, maybe under their own top-level heading. I worry that could be a can of worms that makes it harder to navigate both sets of resources. (although to my knowledge there is no Sapper awesome list yet)
- I made issue #9 to track my fixing any other namespace problems. Thank you for fixing these!

**Comment by ryanatkn** [comment]
I made those little changes in [this commit](https://github.com/ryanatkn/awesome-svelte-resources/commit/f6e9027ea3e3a0cdaaf9cbd55971882bd6268771), mainly moving a lot of stuff to the integrations section, and removing `sapper-httpclient`. I'm probably going to merge the integrations and components sections next, after making sure all of the other npm namespaces are correct. Thank you again!

**Comment by ryanatkn** [comment]
I noticed that few of your projects mention a license. It looks like some mention MIT in the readme, but in the ones I checked didn't see license files or a license field in `package.json`.

I also merge the sections I discussed above. Any feedback is welcome.

**Comment by antony** [comment]
@ryanatkn thanks for that - apologies for not replying sooner, a bit snowed under at the moment.

I have never really paid attention to licensing, but it's a good point. I'll add license files.

**Pull request merged**
